### PR TITLE
Android integration

### PR DESCRIPTION
**Pull request by G10h4ck**
Added android contact integration ( RetroShare contacts display on android contact list )
To make this possible a lot of change on the code had to be done, with the benefit that now more server are supported in parallel.

Missing some cleaning on MainActivity

This pull request is more aimed to call electron attention that to be really merged, and to ask to you that if you do further development please take in account this clone with new features otherwise future merge will need a lot of work...

The part that in the documentation is indicated as crossplatform ( indipendent from android ) is not like that it uses androi Handler, so or we rewrite that parts or we don't say it is android indipendent ( i prefer the first )

### CODE REVIEW

**Comment by G10h4ck** [comment]
This thing is now outdated and kept just as studying material for an eventual future Android Contact list integration

**Comment by jlstanus** [comment]
So now what's the best client for RS?

**Comment by G10h4ck** [comment]
https://github.com/RetroShare/RetroShare/blob/master/README-Android.asciidoc

**Comment by jlstanus** [comment]
WOw nice!! Very nice. So i hope release very soon

**Pull request closed without merging**
